name: Build Android

on:
    push:
        branches:
            - main
jobs:
    build-android:
        name: Build Android
        runs-on: ubuntu-latest
        steps:
            - name: Clone Repository
              uses: actions/checkout@v3

            - name: Setup Java 11
              uses: actions/setup-java@v3
              with:
                java-version: '11'
                distribution: 'temurin'
                architecture: x64
                cache: gradle

            - name: Setup Android SDK
              uses: android-actions/setup-android@v2

            - name: Validate Gradle
              uses: gradle/wrapper-validation-action@v1

            - name: Install NodeJS
              uses: actions/setup-node@v3
              with:
                node-version: '18'
            
            - name: Install Packages
              run: yarn

            - name: The build process has started.
              run: |
                cd android
                ./gradlew assembleRelease

            - name: Upload build
              uses: actions/upload-artifact@v3
              with:
                name: Android Release APK
                path: android/app/build/outputs/apk/release/app-release.apk

            - name: Install Firebase CLI
              run: curl -sL https://firebase.tools | bash

            - name: Upload to App Distribution
              run: |
                firebase appdistribution:distribute android/app/build/outputs/apk/release/app-release.apk \
                --token 1//0eP_qyJM1cj-ICgYIARAAGA4SNwF-L9IrOu7pcgU4gNeXc3kxRkxzmeVKZASunadbC8iMospuSZYzEZy7pLMwP_MdMGgzggtxKmU \
                --app 1:440709677408:android:009487b34f0d2fff511e05 \
                --release-notes-file "./qateam/release-note.txt" \
                --testers-file "./qateam/testers.txt"
            
           
                
       
  
    

