name: Continuous Integration

on:
    pull_request:
        branches:
            - develop
jobs:
    test-lint:
        name: Test Lint
        runs-on: ubuntu-latest
        steps:
            - name: Setup Java
              uses: actions/setup-java@v3
              with:
                distribution: 'temurin'

            - name: Setup Android SDK
              uses: android-actions/setup-android@v2

            - name: Clone Repository
              uses: actions/checkout@v3
              with: 
                fetch-depth: 2

            - name: Install NodeJS
              uses: actions/setup-node@v3
              with:
                node-version: '18'
            
            - name: Install Packages
              run: yarn

            - name: Execute test lint
              run: yarn test:lint
           
                
       
  
    

